# Generated by Django 4.0.1 on 2022-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./static/company/images/hire.png', upload_to='company/profile'),
        ),
    ]
