# Generated by Django 4.0.1 on 2022-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='', upload_to='cell/posts'),
        ),
    ]
