# Generated by Django 4.0.1 on 2022-02-13 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0008_profile_location_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
