# Generated by Django 4.0.1 on 2022-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cell', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='./static/cell/images/hire.png', upload_to='cell/posts'),
        ),
    ]
